[[redirects]]
  from = "/"
  to = "/movie"
  status = 301

[[redirects]]
  from = "/movie/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/external-redirect"
  to = "https://hng-task2-temi.netlify.app/"
  status = 301
